### ISSUE TITLE
Question - What is the IRC channel? 

### ISSUE THREAD

**Issue by spuder** [SimpleFinance/chef-handler-influxdb#2]
The readme says

```
Hop on ##simple on Freenode with any questions or concerns.
```

Is this a private channel, or not used anymore? I've tried joining #simple and ##simple on chat.freenode.net but there are 0 active users.

**Comment by jdinthe** [comment]
Hey @spuder, not sure what's up here. There's 13 of us in `##simple` on Freenode at present ... doesn't appear to be invite-only either.

**Comment by spuder** [comment]
Thanks, Got it worked out.
